version: '2'
services:
  db:
    build: cartodb-postgis
    image: carto-db
    expose:
      - 5432
  maps-api:
    build: cartodb-windshaft
    image: carto-maps-api
    links:
      - db:db
      - redis:redis
    expose:
      - 8181
  sql-api:
    build: cartodb-sql-api
    image: carto-sql-api
    links:
      - db:db
      - redis:redis
    expose:
      - 8080
  web:
    build: cartodb-web
    image: carto-web
    links:
      - sql-api:sql-api
      - maps-api:maps-api
      - db:db
      - redis:redis
  redis:
    image: redis
    expose:
      - 6379
